### ISSUE TITLE
devious debug trace on Linux OpenSUSE

### ISSUE THREAD

**Issue by dominig** [seandepagnier/climatology_pi#68]
Since V 5.0, Climatology let in the opencpn.log file the following trace under Linux OpenSUSE.
Does not look anygood.

2:05:30 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind01weatherrouting
22:05:30 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind02
22:05:30 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind03
22:05:30 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind04
22:05:30 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind05
22:05:30 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind06
22:05:31 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind07
22:05:31 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind08
22:05:31 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind09
22:05:31 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind10
22:05:31 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind11
22:05:31 CEST: climatology failed to read: /home/dominig/.opencpn/plugins/climatology_pi/data/wind12

**Comment by rgleason** [comment]
Dominig, 
I am sorry about this. We seem to be fixing things that were previously fixed. 
We went through a whole process about climatology data, and Pavel suggested using a Module.
The operations are a little different, and perhaps that is what is causing a problem.
Sean does not want to have to download and upload binaries all the time on slow connections.

See this closed thread at the bottom please.
The plugin still supposed to have the download feature in it, so that if there is no data, it will automatically start downloading if the data does not exist. 

Now perhaps that feature is not working for OpenSus?
Or perhaps the data has not been included, because it is now in the "Module"?

See
https://github.com/seandepagnier/climatology_pi_data/tree/b2f26b6935712665eefd1652e4a70384a645b526
It is another git repos that is a data sub module.
I don't get half this stuff, but maybe you can figure it out.
Sean said I did not have to include data in my repos because the submodule will do it.

**Comment by dominig** [comment]
Hello,
I found that the /usr/share/opencpn/plugins/climatology_pi/data/module installs wind and current data correctly in a protected (nned to be root to write in) directory
  /usr/share/opencpn/plugins/climatology_pi/data/
That looks correct to me, plug-in finds the data and use it.
So the error in the log is minor

Not downloading anything at plug-in startup is certainly a very valid concept that should be kept.

**Comment by rgleason** [comment]
Thanks,
Not downloading anything at plug-in startup is certainly a very valid concept that should be kept.
(IE: Including the 6.8mb of data files is a good thing to do.)
Thanks
Should this be closed now dominig?
